name: build_masterpro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.0
  get_it: ^8.0.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  flutter_svg: ^2.0.9
  provider: ^6.0.0
  google_sign_in: ^6.2.2
  google_maps_flutter: ^2.9.0
  logger: ^2.4.0
  fl_chart: ^0.69.2
  image_picker: ^1.1.2
  file_picker: ^6.1.1
  firebase_storage: ^11.5.6
  uuid: ^4.5.1
  path_provider: ^2.1.5
  path: ^1.8.0
  flutter_webrtc: ^0.9.47
  intl: ^0.18.1
  url_launcher: ^6.1.14
  firebase_database: ^10.3.8
  local_auth: ^2.1.5
  geolocator: ^10.1.0
  flutter_spinkit: ^5.1.0
  flutter_riverpod: ^2.6.1
  flutter_cache_manager: ^3.3.1
  share_plus: ^7.1.0
  timeago: ^3.7.0
  flutter_slidable: ^3.1.1
  permission_handler: ^11.3.1
  logging: ^1.3.0
  pdf: ^3.11.1
  open_file: ^3.5.10
  flutterfire_cli: 1.0.1
  win32: ^5.9.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  cached_network_image: ^3.3.1
  agora_rtc_engine: ^6.0.0
  connectivity_plus: ^6.0.0  
  flutter_dotenv: ^5.1.0 
  flutter_email_sender: ^6.0.2
  mailer: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/icon_logo.png"
  adaptive_icon_background: "BLACK"

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/construction_logo.svg
    - assets/icons/google_logo.svg
    - assets/icons/icon_logo.png