name: build_masterpro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.0
  get_it: ^8.0.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  flutter_svg: ^2.0.9
  provider: ^6.0.0 
  google_sign_in: ^6.2.2
  google_maps_flutter: ^2.9.0 
  logger: ^2.4.0
  fl_chart: ^0.69.2
  image_picker: ^1.1.2 
  file_picker: ^8.1.4
  firebase_storage: ^12.3.6
  uuid: ^4.5.1
  path_provider: ^2.1.5
  path: ^1.8.0  
  flutter_webrtc: ^0.12.2
  intl: ^0.18.1
  url_launcher: ^6.1.14
  firebase_database: ^11.1.6
  local_auth: ^2.1.5
  geofencing_api: ^2.0.0
  geolocator: ^13.0.1
  gantt_chart: ^0.3.0
  flutter_spinkit: ^5.1.0 
  flutter_riverpod: ^2.6.1
  flutter_cache_manager: ^3.4.1
  share_plus: ^10.1.2
  timeago: ^3.7.0
  flutter_slidable: ^3.1.1
  permission_handler: ^11.3.1
  logging: ^1.3.0
  pdf: ^3.11.1
  open_file: ^3.5.10
  flutterfire_cli: ^1.0.0
  win32: ^5.9.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/icon_logo.png"
  adaptive_icon_background: "BLACK"  # White background

  assets:
    - assets/icons/construction_logo.svg
    - assets/icons/google_logo.svg
    - assets/icons/icon_logo.png
